name: Deploy tutorial-vue to GH pages
on:
  push:
    branches: [ main ]
  # enables manual runs
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # $GITHUB_WORKSPACE
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install  # installs dependencies
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: dev  # builds the app
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages  # the branch for the deployment
          folder: dist  # the folder getting deployed
